language: julia
os:
  - linux
  - osx
julia:
  - "1.0"
  - "1.1"
  - "nightly"
env:
  - PYTHON=   # Always use Conda
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false

before_install:
  # Apparently the asdf.py package needs jsonschema>=2.3<=2.6, but
  # sometimes jsonschema 3.0.1 will be installed. I assume that
  # someone should fix the "asdf.py" package instead...
  - conda add 'jsonschema>=2.3<=2.6'
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - conda list
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
  - conda list
  - julia -e 'using Pkg; Pkg.build()'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ASDF")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
#  - julia -e 'using Pkg; cd(Pkg.dir("ASDF")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
